### ISSUE TITLE
Chart2D throws System.OverflowException when using Values close to decimal.MaxValue

### ISSUE THREAD

**Issue by PawelTroka** [PawelTroka/Computator.NET#6]
When using Values (either xmin, xmax, ymin, ymax or f(x) value) close to decimal.MaxValue or decimal.MinValue

```
    System.OverflowException: Value was either too large or too small for a Decimal.
       at System.Decimal..ctor(Double value)
       at System.Windows.Forms.DataVisualization.Charting.Axis.GetRequiredLabelSize(ChartGraphics chartGraph, Single maxLabelSize, Single& resultSize)
       at System.Windows.Forms.DataVisualization.Charting.Axis.Resize(ChartGraphics chartGraph, ElementPosition chartAreaPosition, RectangleF plotArea, Single axesNumber, Boolean autoPlotPosition)
       at System.Windows.Forms.DataVisualization.Charting.ChartArea.Resize(ChartGraphics chartGraph)
```

**Comment by PawelTroka** [comment]
Resolved easily by limiting max and min values for Chart2D in commit 775b49c71278c9e1c84164ec5eaab53bcff04b86.
